### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by WelshBanana** [FredyH/MySQLOO#100]
Upon updating the MySQLOO with a newer version my game server just outright has a seizure and begins killing core parts such as the game mode and any important scripts. I don't have the first idea as to why this is happening as there are no details on it anywhere I check I just know through trial and error that it is MySQLOO that is causing it.

Thanks, 
Brooke

**Comment by FredyH** [comment]
The last update (9.7.3) fixed a crash issue, are you using the latest version?

**Comment by WelshBanana** [comment]
Yes, it still happens, I'd be happy to show you some time as it's quite hard to explain, if you have a discord or something I can contact you by that would be great.

**Comment by FredyH** [comment]
Sure, you can message me on Discord: Fredy#0988

**Comment by WelshBanana** [comment]
> 

There's a missing tag in the discord

**Comment by FredyH** [comment]
The formatting cut it off, I fixed it.

**Comment by WelshBanana** [comment]
Right, I've sent a friend request, we'll have to hop in call some time so I can show you

**Comment by WelshBanana** [comment]
Problem resolved, a file was causing the issue.
