### ISSUE TITLE
Module won't load

### ISSUE THREAD

**Issue by bdawg009** [FredyH/MySQLOO#101]
I have Prometheus installed on my server, which I have installed on a VPS and it needs MySQL but it always says that the MySQL or tmysql isn't installed, which it is. I have the .dll file in my garrysmod/garrysmod/lua/bin folder, and I do not have libmysql installed. I have contacted my VPS host and they cannot help me. They said to contact the owner of the addon that wont work properly. Maybe I'm doing something stupid or I have one tiny underlying problem but I don't see what it would be. I don't have any console errors either. Everything works smoothly except this.

**Comment by Kefta** [comment]
What OS/arch are you on and what's the name of the module?

**Comment by bdawg009** [comment]
I am on Windows 64 bit and it is just MySQLoo the file name is gmsv_mysqloo_win64.dll

**Comment by Kefta** [comment]
Is your server on the x86_64 branch or main?

**Comment by FredyH** [comment]
This is often caused by launching the 32 bit version of srcds on the 64 bit branch, you should always download both 32 and 64 bit versions of the module and place them in your bin folder, just to rule out that mistake.

**Comment by bdawg009** [comment]
@FredyH I just tried that and it did not work. Also @Kefta it is the main branch not the x86, also correct me if I'm wrong but isn't x86 actually 32 bit?

**Comment by FredyH** [comment]
What's the error that is printed in your console?
Maybe your prometheus is outdated and does not find the 64 bit version of the module?

**Comment by bdawg009** [comment]
[Prometheus error at 12:06:42 - 21/01/2022] Neither MySQLoo or tmysql4 module could be loaded! Please go to  http://wiki.prometheusipn.com/index.php?title=Installation:lua_prerequisites  and follow the instructions on how to install MySQLoo or tmysql4! Your server is windows OS, so download the files for that OS!
||||||||||||||||||||||||||||||||||
||                              ||
||      Loading  Prometheus     ||
||                              ||
||||||||||||||||||||||||||||||||||
||                              ||
||      Couldn't load DB module ||
||      Add-on will not work    ||
||                              ||
||||||||||||||||||||||||||||||||||

@FredyH

**Comment by FredyH** [comment]
Try launching the 32 bit version of srcds and see if that works.
I have a suspicion that prometheus is really outdated and does not support the 64 bit module.

**Comment by bdawg009** [comment]
Do I do this by using "-32bit" in my server console?

**Comment by bdawg009** [comment]
@FredyH I have srcds.exe and start.bat. Am I looking in the wrong place?

**Comment by Kefta** [comment]
Main branch doesn't have the x64 SRCDS. Could try using the x86_64 branch and see if the module is recognised then?

**Comment by FredyH** [comment]
It means that you have a 32 bit version of the server, so you need to download the 32 bit version of the module rather than the 64 bit version.
