### ISSUE TITLE
Database:ping() causes entire server to permanently freeze

### ISSUE THREAD

**Issue by ApertureDevelopment** [FredyH/MySQLOO#103]
I got multible bug reports for MSync 2 that when someone is trying to use the addon without a database connection, they can't join their server. While looking into it, I found this to be caused by how I detect the database status. If `Database:ping` is executed without a database setup, the entire server freezes until the server is restarted.

Since it is mentioned ``This will freeze your server for at least 2 times the pingtime to the database server if the connection is down`` I am not sure if this is a bug or not, because this would effectively never return any value when the database is not connected. I have waited for 30 minutes but the server never did unfreeze.

**Comment by FredyH** [comment]
I just released a new version of MySQLOO that hopefully fixes this issue.
If there is still some bug with the module freezing the server when waiting on a query or the database connection to finish, please reopen this issue.
