### ISSUE TITLE
Integration of `LuaORM` for use with `MySQLOO`

### ISSUE THREAD

**Issue by mo3g666** [FredyH/MySQLOO#104]
Hello FredyH! Since your MySQL module is the most common for use in Gmod, I thought about the convenience of working for the end user. 
I came across an implementation of `ORM` in the `Lua` language, which initially works with the `LuaSQL` library and began to modify it for Gmod and your library, but ran into some difficulties. 
Could you help me with this and contact me where it would be convenient for you ?

**Comment by FredyH** [comment]
The LuaORM is based on synchronous SQL calls, i.e. it starts a query and then waits for it to finish before returning.
mysqloo is entirely async and callback based, which means getting it to work the same way will be very hard (the best way would be using coroutines), but either way, it would be a significant change from how LuaORM works.

If you want to discuss it, you can add me on [Steam](https://steamcommunity.com/id/fredyh).

**Comment by mo3g666** [comment]
Sent you a request

**Comment by mo3g666** [comment]
You have a crowded list of friends ) Maybe you use Discord ? Drogo#9807
