### ISSUE TITLE
The module cannot be loaded. Couldn't load module library! ( .)

### ISSUE THREAD

**Issue by Wilfol** [FredyH/MySQLOO#105]
Hello! I apologize in advance for my text because I use google translator.
I had such a problem, when I run the module on srcds x32 on my Windows 10 x64, there are no problems, but when I run the same assembly on Windows Server 2019 x64, it displays an error when I try to run the module:
Couldn't load module library! ( .)
Again, I repeat, everything works fine on my home PC.
I tried to install different versions of vcredist 2022, 2019, 2017, 2015, 2013, 2008 both all together and separately, nothing helped.
The module is installed along the path: garrysmod/lua/bin/
The bin folder contains the following files:

gmsv_cryptrandom_linux.dll
gmsv_cryptrandom_win32.dll
gmsv_enginespew_linux.dll
gmsv_enginespew_win32.dll
gmsv_fps_linux.dll
gmsv_fps_win32.dll
gmsv_mysqloo_linux.dll
gmsv_mysqloo_win32.dll
gmsv_slog_linux.dll
gmsv_tmysql4_linux.dll
gmsv_tmysql4_win32.dll

I tried to install different versions of the module, including the beta version, but everywhere I write one error: Couldn't load module library! ( .), when calling lua require( "mysqloo" ).
I also want to note that if on my hosting I take not a virtual machine, but a game hosting from ubuntu on board, then the module is loaded normally, but I need it preferably on a Windows server 2019/2016

Thank you for understanding, I hope I'm not too distracting

P.s. I also tried to install both 32 and 64 bit versions of the module.
>print(jit.os, jit.arch)...
Windows x86

**Comment by FredyH** [comment]
You are likely missing the 32 bit version of some vcredis (they have both 32 and 64 bit versions).
You should be able to find out which one is missing by using [DependencyWalker](https://www.dependencywalker.com/)

**Comment by Wilfol** [comment]
Wow! Really. The problem caused such a stupid mistake. Everything works now, thanks for the tip♥
