### ISSUE TITLE
Very long Connectivity test: result=Connected, in progress=0

### ISSUE THREAD

**Issue by PrikolMen** [FredyH/MySQLOO#108]
After starting the server is written into the console:
Connectivity test: result=Connected, in progress=0

And it lasts 10 minutes

**Comment by FredyH** [comment]
Can you please provide some more detail? These messages are not printed by the module so it must be some addon you are using.

**Comment by FlorianLeChat** [comment]
This message is very likely related to [gluapack](https://www.gmodstore.com/market/view/7724) and not to MySQLOO.

![image](https://user-images.githubusercontent.com/26360935/162561753-f74bf7eb-e725-4ec6-b12d-ddf79a6a5cd5.png)

**Comment by PrikolMen** [comment]
I used mysqloo in conjunction with gmodadminsuite, after setting up the config file I ran it. The initial upload passed, this message appeared and the server stopped loading and doing anything, the processor activity dropped to 0 and 200 MB RAM was used. This continues for 5 - 10 minutes after which the server continues to boot.

**Comment by Kefta** [comment]
It's still not from mysqloo.
