### ISSUE TITLE
setAutoReconnect doesn't always seem to work

### ISSUE THREAD

**Issue by HavannaFR** [FredyH/MySQLOO#109]
Hi,

I currently have a problem that happens rarely but still happens from time to time and is particularly disturbing.
I could see in my logs that some requests failed to execute and left an error in the console:
`[ULIB] Query ERROR: The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.`

I did setAutoReconnect(true) before the connect()

Do you think there is a problem with the setAutoReconnect() function?

Thank you.

**Comment by FredyH** [comment]
Sorry for the late reply.
I have tested the issue and it does appear to be broken. The first query always seems to fail after the connection was lost.
I am kind of unsure why this is happening since mariadb's/mysql's auto-reconnect feature should reconnect immediately. I will have to test some things and then get back to you.

**Comment by HavannaFR** [comment]
> Sorry for the late reply. I have tested the issue and it does appear to be broken. The first query always seems to fail after the connection was lost. I am kind of unsure why this is happening since mariadb's/mysql's auto-reconnect feature should reconnect immediately. I will have to test some things and then get back to you.

No worries, thank you very much for your answer, hope you can find a solution soon :)
In the meantime I think I will send useless requests from time to time to maintain the connection!

**Comment by FredyH** [comment]
I just released a new version that fixes the issue. If it does not solve your issue, please let me know!
