### ISSUE TITLE
MySQLoo don't connect to database

### ISSUE THREAD

**Issue by LeandroCRL** [FredyH/MySQLOO#111]
Hello.
I'm trying to open a server with MySQLoo, but the problem is that nothing happens when I put the Modules, no error, but it doesn't connect to my Database .
![imagem_2022-06-17_062938846](https://user-images.githubusercontent.com/59122793/174270660-298dde82-c944-4a18-aeca-4a39346e66b4.png)

```
 66.7 fps  0/ 2 on map     gm_flatgrass
Console initialized.
ConVarRef mat_dxlevel doesn't point to an existing ConVar
Game.dll loaded for "Garry's Mod"
Initializing Steam libraries for Workshop..
WS: No +host_workshop_collection or it is invalid!
Network: IP , mode MP, dedicated Yes, ports 27015 SV / 27005 CL
Error loading cfg/trusted_keys_base.txt
Error loading cfg/pure_server_minimal.txt
PREP OK
Executing dedicated server config file server.cfg
Using map cycle file cfg/mapcycle.txt.
Initializing Steam libraries for secure Internet server
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
Connection to Steam servers successful.
   Public IP is 
Assigned anonymous gameserver Steam ID [A-1:3397358601(20555)].
VAC secure mode is  
activated.``

**Comment by FredyH** [comment]
You need a bot or a player on the server for the callbacks to be run, otherwise you will never get any messages until someone joins.

**Comment by Kefta** [comment]
You can also disable think hibernation so it runs without players. I forgot the exact convar name but if you put "find hibernate" in console, it should come up.

**Comment by FlorianLeChat** [comment]
> I forgot the exact convar name but if you put "find hibernate" in console, it should come up.

It's `sv_hibernate_think`
