### ISSUE TITLE
The module cannot be loaded. Couldn't load module library!

### ISSUE THREAD

**Issue by Tester101TWO** [FredyH/MySQLOO#112]
Hi srcds displays an error when I try to run the module:
Couldn't include file! 
![ebc89f18c0ab2fc790353ad52c0e1026](https://user-images.githubusercontent.com/110140572/181395258-79ab0001-eaed-47e1-b163-12263793fa1d.png)

I have tried both 32 BIT srcds with all the modules and 64 BIT srcds with all the modules.
I have tried old versions of mysqloo including libmysql's
I tried to install different versions of vcredist 2022, 2019, 2017, 2015, 2013, 2008 both all together and separately.

![80285d2d48fe90c30696080960fee8b2](https://user-images.githubusercontent.com/110140572/181395932-c442e1ef-42f9-49e9-a554-de4377e9cb11.png)

The module is installed along the path: garrysmod/lua/bin/
and for 64 bit the modules in  C:\server\bin
The bin folder contains the following files:

gmsv_mysqloo_win32.dll
gmsv_mysqloo_win64.dll

I tried to install different versions of basically everything, including the beta version but everytime it wrote back ( Couldn't load module library! )

![d0e1915e96d541d73e76907783339fc5](https://user-images.githubusercontent.com/110140572/181395841-0118daf8-66ef-4ac1-ac38-6907f6dcb7f1.png)

I believe it has to be a dependency problem at this point cause I have tried literally everything I heard about dependency walker but I have ZERO clue how to use it. Looked up a few videos and havent gotten anywhere figured I should throw a photo of that I used the most up to date win32 version as a reference 
![63b7ca76f898cd1da7ec14b29c65a94a](https://user-images.githubusercontent.com/110140572/181396406-9bf0f1bd-badb-4023-9508-d77cfd841915.png)

![5f8b2fcc9aac9aca196bf0bfc07de023](https://user-images.githubusercontent.com/110140572/181399460-50d2f9c3-9864-439f-b830-26d57baf62e4.png)

Thank you

**Comment by FredyH** [comment]
The first error you sent states that the DLL was not found in the correct folder. Are you sure you placed it in the correct folder? It should be %server_directory%/garrysmod/lua/bin for both the 32 and 64 bit versions of the module.

**Comment by Tester101TWO** [comment]
Wow... I swear I've looked through threads and threads I've moved files everthing but never did I know to go into %server_directory%/garrysmod/lua/bin I didnt have a bin file there so I made one dropped the dll in and it worked you are a life saver wow... wow! I even put the dll in multiple areas like %server_directory%/bin %server_directory%/garrysmod/bin thank you!

**Comment by viral32111** [comment]
> but never did I know to go into %server_directory%/garrysmod/lua/bin 

[Reading the install instructions always helps.](https://github.com/FredyH/MySQLOO#install-instructions)
