### ISSUE TITLE
[mysql] Unable to connect to the database

### ISSUE THREAD

**Issue by LeandroCRL** [FredyH/MySQLOO#114]
![imagem_2022-08-22_001832134](https://user-images.githubusercontent.com/59122793/185831858-4e215aa2-8ecf-4dc3-8a78-eb4544bfc5f3.png)
 
My local server works fine but for some reason the linux server I use in Pterodactyl doesn't connect to my database in phpmyadmin

![imagem_2022-08-22_002123537](https://user-images.githubusercontent.com/59122793/185832108-6972d253-7227-410d-8e5e-5fc5fb48e894.png)

**Comment by FredyH** [comment]
This must be due to a misconfigured database setup, either in your connection data or the database isn't accessible to the outside.
Either way, this is not an issue of MySQLOO but rather of your setup.
