### ISSUE TITLE
Query.onError missing 3rd `sql` arg

### ISSUE THREAD

**Issue by 2048khz-gachi-rmx** [FredyH/MySQLOO#115]
Functionality seems to have been lost between 9.6 and 9.7, but the docs still reference the `sql` argument.

### 9.6:
https://github.com/FredyH/MySQLOO/blob/abddaf62c8cfd72d940baf43eee10ee091dd8b45/MySQLOO/source/Query.cpp#L30-L33

### 9.7:
https://github.com/FredyH/MySQLOO/blob/b1d29b5a4f6aa44f357aa683aba6da50afc62827/src/lua/LuaIQuery.cpp#L80-L91

### Docs:
https://github.com/FredyH/MySQLOO/blob/b1d29b5a4f6aa44f357aa683aba6da50afc62827/README.md?plain=1#L217-L218

**Comment by FredyH** [comment]
This was indeed lost with the latest major update, I fixed it in 9.7.6.
Thanks for reporting it!
