### ISSUE TITLE
Query.onSucess(q,data) should be Query.onSucess(data)

### ISSUE THREAD

**Issue by xxPhilipxx** [FredyH/MySQLOO#116]
Query.onSucess(q,data) should be Query.onSucess(data)

**Comment by bigdogmat** [comment]
It's called with the query as the first argument. Are you saying it shouldn't?

**Comment by FredyH** [comment]
As @bigdogmat pointed out, this is expected behaviour since you can then do
```LUA
function query:onSuccess(data)
    -- code
end
```
and it naturally integrates with Lua's self parameter
