### ISSUE TITLE
MySQLOO not loading, both 32/64 bits tested

### ISSUE THREAD

**Issue by datTaster123** [FredyH/MySQLOO#117]
So I'm trying to run my server(s) on MySQLOO on an external database, I've registered all the information and allowed access through web host panel to all corresponding ip addresses. 

I've tried both 32 & 64 bit, placed inside garrysmod/lua/bin and still doesn't want to load? 

`gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:133: Couldn't load module library! (The specified module could not be found.)`
`gamemodes/darkrp/gamemode/modules/fadmin/fadmin/motd/sv_init.lua:14: attempt to index global 'MySQLite' (a nil value)`
`gamemodes/darkrp/gamemode/init.lua:113: attempt to index global 'MySQLite' (a nil value)`

When both bits installed, I use command _'lua_run require("mysqloo")'_ and comes back with:
`[ERROR] lua_run:1: Couldn't load module library! (The specified module could not be found.)`

Both 32 & 64 installed, clean server install, clean darkrp & darkrpmodification so I'm confused why it isn't working

**Comment by FredyH** [comment]
Hi, this error likely means that the file is not in the right location. Can you show me which files you put in the lua/bin folder?
