### ISSUE TITLE
Issue with server

### ISSUE THREAD

**Issue by rbreslin18** [FredyH/MySQLOO#119]
```
Loading mysqloo module... done!
[ERROR] gamemodes/perp/gamemode/sv_hooks.lua:4: attempt to call field 'Query' (a nil value)
  1. sendOnline - gamemodes/perp/gamemode/sv_hooks.lua:4
   2. unknown - gamemodes/perp/gamemode/sv_hooks.lua:69

Any reason why this may be happening? I'm currently on the journey of fixing the an old perp gamemode(way more annoying than I thought lol) and was in the process of trying to get the DB to work properly and keep running into this error. Help would be great thanks.

**Comment by rbreslin18** [comment]
thanks for quick response, im going to try and get tmysql working properly instead of rewriting everything since im lazy

**Comment by FredyH** [comment]
You can also try to use the tmysql drop in replacement to emulate tmysql using mysqloo.
It is located in the lua subfolder of this project, but I cannot guarantee it still works properly.

**Comment by rbreslin18** [comment]
Ill give it a go, i found the old tmysql3 online and it seems to work with this old legacy perp code.
