### ISSUE TITLE
MySQLOO's Linux ddl makes a gmod server unable to enter

### ISSUE THREAD

**Issue by blancovn** [FredyH/MySQLOO#120]
Hello, I set MySQLOO in my GMod's Linux server. The problem is when I find that I am unable to enter my server because it says "password failed", while I didn't set any password in order to join my server.

When I removed the mysqloo dll from y server and I restarted, I was able to join with no other issue than staff plugins not working because of missing dll. 

I install the dll = My server asks for a password I didn't even set up. I remove the dll =  My plugins don't work but I can join.

Can you figure this issue out? Thank you.

**Comment by Kefta** [comment]
This module does not set a server password - perhaps one of your addons is doing it after it requires the module. Try removing all of them except for the module to verify this, then add them back in chunks or one-by-one to narrow down the source.

**Comment by blancovn** [comment]
Hello, I removed Simple Admin Manager addon (the addon that was causing troubles) and it worked. Now, do you know if said addon can manage server password and if so, to remove said permission.

**Comment by Kefta** [comment]
I do not know anything about the addon. I would dive into the code (file search for any instances of "password") or contact the addon's author(s).
