### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SasnyParen** [FredyH/MySQLOO#121]
After update Garry's mod, mysqloo not working, what could be the problem?

**Comment by FredyH** [comment]
Are you on 32 or 64 bit?

**Comment by SasnyParen** [comment]
32 bit

**Comment by FredyH** [comment]
I am on 32 bit on the latest gmod version and it does work for me, what errors are you getting?

**Comment by FredyH** [comment]
What does it mean that it broke?
