### ISSUE TITLE
MYSQLOO load fail

### ISSUE THREAD

**Issue by Andrekan1** [FredyH/MySQLOO#122]
Adding `require("mysqloo")` in autorun code creates an error in console `Couldn't load module library! (The specified module could not be found.)`. Server runs on Win 64bit srcds, 64bit module installed correctly in folder `garrysmod/lua/bin`.

**Comment by FredyH** [comment]
It might be the case that you are missing a visual studio redistributable like in #40
If that one was missing, please let me know and I will add it into the README

**Comment by Andrekan1** [comment]
Yeah, that was a problem. My server did not have it. Problem solved
