### ISSUE TITLE
SQL can break for steam users with non-english characters in their username

### ISSUE THREAD

**Issue by WolfKann** [FredyH/MySQLOO#123]
What the title says, I'm not sure if it's a gamemode specific bug but having non-english based characters in steam/account names breaks the system for some reason. I'm not sure 100% why.

**Comment by FredyH** [comment]
The addon in question is likely not setting the character set to utf8 correctly.
There is a function to do this which you can find in the documentation:
```lua

Database:setCharacterSet(charSetName)
-- Returns [Boolean]
-- Attempts to set the connection's character set to the one specified.
-- Please note that this does block the main server thread if there is a query currently being ran
-- Returns true on success, false on failure

```
