### ISSUE TITLE
Can't find the module.

### ISSUE THREAD

**Issue by Warmarcus** [FredyH/MySQLOO#127]
[casesystem_cases] Couldn't include file 'includes\modules\mysqloo.lua' - File not found or is empty (@addons/casesystem_cases/lua/autorun/shared.lua (line 1))
  1. unknown - addons/casesystem_cases/lua/autorun/shared.lua:1

mysqloo not found! Check if the library is properly installed.
[Warmarcus|3|STEAM_0:0:425895348] Lua Error:

[casesystem_cases] Couldn't include file 'includes\modules\mysqloo.lua' - File not found or is empty (@addons/casesystem_cases/lua/autorun/shared.lua (line 1))
  1. unknown - addons/casesystem_cases/lua/autorun/shared.lua:1

**Comment by 1day2die** [comment]
i have the same issue. how did you fix it?


[ulx_globalbanmodule] Couldn't include file 'includes/modules/mysqloo.lua' - File not found or is empty (@addons/ulx_globalbanmodule/lua/globalban/gb_mysqloo.lua (line 5))
  1. unknown - addons/ulx_globalbanmodule/lua/globalban/gb_mysqloo.lua:5
   2. include - [C]:-1
    3. unknown - addons/ulx_globalbanmodule/lua/autorun/ulx_globalban.lua:9
