### ISSUE TITLE
The latest garrsmod update of today broke mysqloo

### ISSUE THREAD

**Issue by MrCoala** [FredyH/MySQLOO#128]
The garrysmod update of today broke mysqloo. It is basically not useable anymore. Can you have a look into that?

**Comment by WinterPhoenix** [comment]
For context, debug.getregistry was removed, which likely means you just can't get `SPECIAL_REG` anymore

**Comment by WinterPhoenix** [comment]
Update: Make sure you've got the latest version of GMod/SRCDS. It looks like mysqloo is working again with it

**Comment by FredyH** [comment]
I am not sure why mysqloo would be broken by this.
I don't use `debug.getregistry` or `SPECIAL_REG` anywhere as far as I can see, and my local dev server does not seem affected (but this might be because some hotfix is already out?)

**Comment by MrCoala** [comment]
Okay, so i am not sure what is happening right now but the latest update suddenly broke mysqloo.

I just a fresh gmod installation by using steamcmd:

`./steamcmd.sh +login anonymous +force_install_dir ./gmod_test/ +app_update 4020 validate +quit`

I installed the latest gmsv_mysqloo_linux64.dll into: ./gmod_test/garrysmod/lua/bin
Into this directory **/garrysmod/lua/includes/modules** i put the following files from this repo:

connectionpool.lua
mysqloolib.lua
tmysql4.lua


These are the lua errors i got:

> [sw_helper] Couldn't include file 'includes/modules/mysqloo.lua' - File not found or is empty (@addons/sw_helper/lua/server/sv_mysql.lua (line 1))
>   1. unknown - addons/sw_helper/lua/server/sv_mysql.lua:1
>    2. include - [C]:-1
>     3. Include - addons/sw_helper/lua/autorun/init.lua:57
>      4. IncludeFolder - addons/sw_helper/lua/autorun/init.lua:85
>       5. unknown - addons/sw_helper/lua/autorun/init.lua:90
> 
> 
> [sw_helper] addons/sw_helper/lua/server/sv_mysql.lua:1: Module not found!
>   1. require - [C]:-1
>    2. unknown - addons/sw_helper/lua/server/sv_mysql.lua:1
>     3. include - [C]:-1
>      4. Include - addons/sw_helper/lua/autorun/init.lua:57
>       5. IncludeFolder - addons/sw_helper/lua/autorun/init.lua:85
>        6. unknown - addons/sw_helper/lua/autorun/init.lua:90

For that code:

`require('mysqloo')
`

I am pretty confused right now since this is the exact same setupt as my productive server has but it still fails with the latest gmod server files.

**Comment by FredyH** [comment]
Since it appears to work now, I will close the issue. If anyone finds something else wrong with this latest Garry's Mod update, please feel free to re-open.
