### ISSUE TITLE
64 Bit SQLOO showing triggers

### ISSUE THREAD

**Issue by FiBzYDev** [FredyH/MySQLOO#129]
I find a bug with 64 bit sqloo its showing triggers we dont want to see
this bug only happens on 64 bit version

![20240324235552_1](https://github.com/FredyH/MySQLOO/assets/58349075/552d8b6b-a2d1-47c1-afe4-ffb4f5b1a7cc)

![20240324235548_1](https://github.com/FredyH/MySQLOO/assets/58349075/66d66b2a-690d-48d1-8ea9-b13f80b1c892)

**Comment by FredyH** [comment]
This is almost certainly not a consequence of using mysqloo.
It seems more like a bug in the 64 bit branch of gmod. It has received many updates recently that have broken the game so I suggest contacting Rubat in the gmod discord.
