### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Heyter** [FredyH/MySQLOO#130]
`INSERT INTO `items` (`name`) VALUES ('test'), ('test2'), ('test3') RETURNING `id`;`

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near `'RETURNING 'id'' `at line 1

https://mariadb.com/kb/en/insertreturning/

**Comment by FredyH** [comment]
Only MariaDB seems to support insert returning and I suspect you might be connected to a MySQL database.
In any case, this is a query related issue and not an issue with this module.
