### ISSUE TITLE
Symbols In Names

### ISSUE THREAD

**Issue by FrezZyyy** [FredyH/MySQLOO#132]
any form of symbols like hearts, squares etc seem to cause many issues with players data loading. here is an example:

(SAM | MySQL) Query error: Incorrect string value: '\xF0\x9D\x97\xA6\xF0\x9D...' for column `motionrp_darkrp`.`sam_players`.`name` at row 1
stack traceback:
addons/[admin]_sam_154/lua/sam/player/sv_auth.lua:108: in function 'func'
addons/[core]_gmodadminsuite/lua/includes/modules/hook.lua:315: in function 'internal_call'
addons/[core]_gmodadminsuite/lua/includes/modules/hook.lua:334: in function <addons/[core]_gmodadminsuite/lua/includes/modules/hook.lua:331>
[AWarn3] Incorrect string value: '\xF0\x9D\x97\xA6\xF0\x9D...' for column `motionrp_darkrp`.`awarn3_playertable`.`PlayerName` at row 1
addons/[gmodstore]_awarn3_v2.4.4/lua/includes/mysqlite_awarn3.lua:168: Incorrect string value: '\xF0\x9D\x97\xA6\xF0\x9D...' for column `motionrp_darkrp`.`awarn3_playertable`.`PlayerName` at row 1 (INSERT INTO awarn3_playertable ( PlayerID, PlayerName, PlayerWarnings, LastPlayed ) VALUES ( "76561198153705845", "𝗦𝘁𝗶𝗰𝗸𝘀", 0, 1711910483 ))

i had him change his in game name to hopefully fix this. but he originally joined with symbols in name.

**Comment by FrezZyyy** [comment]
he changed his name and reconnected and it reverted back to symbol name

**Comment by FrezZyyy** [comment]
yeah it is an mysqloo issue formatting names, he took out the hearts and it fixed.

**Comment by FredyH** [comment]
This is not a mysqloo issue.
Your table (column) either does not support the UTF characters that were used or you did not set the charset for the connection correctly using
```lua
Database:setCharacterSet(charSetName)
```
