### ISSUE TITLE
Linux x86 Manual Compiling Issues

### ISSUE THREAD

**Issue by CyberSamurai0** [FredyH/MySQLOO#134]
Hello,
I've been attempting to make some minor modifications to the library for my own purposes and therefore need to compile new versions of the DLLs. I was successful in compiling the binaries for Windows but primarily require the Linux x86 build, which I was unable to acquire via the instructions provided in the README.

I first attempted to run CMake using Ubuntu 64-bit (WSL) which produced an x64 binary. I also attempted to modify the Visual Studio configuration to use WSL to achieve these ends, but it only ever produced x64 binaries despite using the built-in linux_x86 toolchain.

I _was_ able to successfully compile the Linux x86 build after spinning up an i386 Debian 12 x86 VM, but received the following error in my attempts to use it within a Garry's Mod server:
`Couldn't load module library! (/lib/i386-linux-gnu/libc.so.6: version GLIBC_2.33' not found (required by /home/container/garrysmod/lua/bin/gmsv_mysqloo_linux.dll))`

I'm obviously not doing this right, but I was hoping you could perhaps provide more documentation on how to effectively and successfully compile the binary files for Linux, which would allow for easier expansion upon your work. Thank you!

**Comment by viral32111** [comment]
Looks like the host/container running the server doesn't have the same glibc version installed that the module was compiled against. Easiest way to get them matching is to run the build on the same distribution & release that the host/container is running. e.g., if the container is Ubuntu 22.04 LTS then try build on a Ubuntu 22.04 LTS VM. Alternatively, update the host/container to the latest glibc version.

For future reference, on the host/container you can check if required libraries are installed by running `ldd /path/to/binary/or/library/file`.

https://sourceware.org/glibc/wiki/Glibc%20Timeline

https://tracker.debian.org/pkg/glibc

**Comment by CyberSamurai0** [comment]
Thanks for your advice, I was able to build a working version using Debian 11 with the same packages as those installed on the server's container.
