### ISSUE TITLE
[Feature Request] rowsAffected (same as affectedRows)

### ISSUE THREAD

**Issue by blobles-dev** [FredyH/MySQLOO#136]
Hi,

Just a little feature request, would be nice to have an alias of :affectedRows() but instead :rowsAffected().
For some reason I keep typing rowsAffected, which is leading me down a rabbit hole of debugging.

I suspect this is very very low priority and I'm cool with that - it would be nice to just have an interchangeable option, but I can live without it.

**Comment by FredyH** [comment]
I believe you can already implement this yourself:
```lua
require("mysqloo")
local MT = FindMetaTable("MySQLOO Database")
MT.rowsAffected = MT.affectedRows
```

**Comment by blobles-dev** [comment]
> I believe you can already implement this yourself:
> 
> ```lua
> require("mysqloo")
> local MT = FindMetaTable("MySQLOO Database")
> MT.rowsAffected = MT.affectedRows
> ```

Wasn't aware of the meta table names, thank you. Saves me 10 seconds of headache :)

**Comment by blobles-dev** [comment]
Actually - isnt that the database object? wouldn't it be for the query?

**Comment by FredyH** [comment]
You are right, it is the query of course. I edited my answer.
