### ISSUE TITLE
Could not find a suitable MySQL module.

### ISSUE THREAD

**Issue by quseless** [FredyH/MySQLOO#139]
After update gmod version (dll file garrysmod/bin server_srv.so):

ERROR: Could not find a suitable MySQL module. Supported modules are MySQLOO and tmysql4.

![image](https://github.com/user-attachments/assets/44d32349-f933-47d6-8e92-8320e0a824f1)

I have all MySQLOO versions in lua/bin folder

How fix that?

**Comment by quseless** [comment]
Using the Linux x32 version does not solve the problem

![image](https://github.com/user-attachments/assets/81c20250-4176-41cf-982e-459bda37a870)

**Comment by quseless** [comment]
When reverting a file garrysmod/bin server_srv.so to a previous version MySQL works, but GMOD does not work correctly

**Comment by FredyH** [comment]
What linux are you running?

**Comment by quseless** [comment]
> What linux are you running?

My host uses linux x86 as you can see in the screenshot above

**Comment by FredyH** [comment]
Yes, but which Linux?

**Comment by quseless** [comment]
> Yes, but which Linux?


I use a hosting service with dedicated resources. I don't have access to a terminal. Steam console only.

How can I find out the Linux version in this case? Thanks for support

**Comment by quseless** [comment]
> Yes, but which Linux?

CentOS
gcc (GCC) 12.2.0

**Comment by FredyH** [comment]
It should work with that configuration.
I don't personally use CentOS but it should be up-to-date enough.
Maybe there is something wrong with the library that you are using, but I have no problem using it on my server (both 32 and 64 bit).

**Comment by quseless** [comment]
> It should work with that configuration.
> I don't personally use CentOS but it should be up-to-date enough.
> Maybe there is something wrong with the library that you are using, but I have no problem using it on my server (both 32 and 64 bit).

But it doesn’t work. everything is fine with the server files, when using the previous version of the bin files of the game mysqloo works, how can this be?

**Comment by FredyH** [comment]
Which previous version of the bin files have you tried?

**Comment by quseless** [comment]
> Which previous version of the bin files have you tried?
[bin.zip](https://github.com/user-attachments/files/16825823/bin.zip)

server.so and server_srv.so 21.01.2024

**Comment by FredyH** [comment]
I am using the module with the latest gmod update and it works for me on Linux (both 32 and 64 bit).
I don't think this is related to the module because nothing was changed since then, I suggest asking for support from your host/library author.
