### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by masterstreamer** [FredyH/MySQLOO#17]
Hi, I'm not so similar with gmod, so I understanded that I have to place the libmysql.dll at root directory (where srcds.exe is) and place the whole mysql-folder (downloaded as zip directly the full project) into garrysmod/addons and the gmsv_mysqloo_win32.dll into garrysmod/lua/bin

But tttdamagelogs cannot be set up with mysql correctly. What is the problem here? How can I test if mysqloo works?

**Comment by Kefta** [comment]
Can you post the errors you get?

**Comment by masterstreamer** [comment]
```
[ERROR] addons/tttdamagelogs-3.1.0/lua/damagelogs/server/oldlogs.lua:23: attempt to index global 'mysqloo' (a nil value)
  1. unknown - addons/tttdamagelogs-3.1.0/lua/damagelogs/server/oldlogs.lua:23
    2. include - [C]:-1
      3. unknown - addons/tttdamagelogs-3.1.0/lua/damagelogs/server/init.lua:23
        4. include - [C]:-1
          5. unknown - addos/tttdamagelogs-3.1.0/lua/autorun/damaglog_autorun.lua:20
```
This is the only error I get, one said me this is because mysqloo isn't installed.

**Comment by Kefta** [comment]
Are there any earlier errors about the module failing to be required?

**Comment by masterstreamer** [comment]
No, nothing. Theres a message including addon file system mysqloo

**Comment by Kefta** [comment]
Is the code to this addon public?

**Comment by masterstreamer** [comment]
@Kefta Which code do you mean? Say me a file and I will give it to you

**Comment by FredyH** [comment]
You should contact whoever made that plugin and ask them how to install it properly, I don't think this is an issue of mysqloo.

**Comment by masterstreamer** [comment]
@FredyH is there a way to check if mysqloo is working? Because the author of the plugin says this error is shown if mysqloo isn't installed properly.

**Comment by FredyH** [comment]
Make sure to go through the install instructions again, also pay attention to file permissions.

**Comment by masterstreamer** [comment]
@FredyH the only things I had to do is to set the libmysql.dll to root directory and gmsv_mysqloo_win32.dll into garrysmod/lua/bin, this is all, right? Which file permissions should I give?
