### ISSUE TITLE
Update the project against MySQL v8.0

### ISSUE THREAD

**Issue by kklouzal** [FredyH/MySQLOO#20]
MySQL version 8.0 has been released and offers major performance and security upgrades.

Will the project be updated against this new version?

**Comment by FredyH** [comment]
the current module should work just fine with mysql 8,0. Are there any features that are new and you want added?

**Comment by FredyH** [comment]
Is this related to mysql8? Please post some steps to reproduce

**Comment by monster010** [comment]
Yes, I have notified him

**Comment by Kamshak** [comment]
It's not the shop printing it @FredyH, i believe it's printed by gmod and it happens when using MySQLOO. Don't have anything more specific but it has been around since before there was a pointshop (https://gmod.facepunch.com/f/gmoddev/nkvn/Mysql-related-No-MetaName-string-type-for-userdata-AGH/1/)

**Comment by Kamshak** [comment]
If it helps at all this is how all queries are created: https://github.com/Kamshak/LibK/blob/master/lua/libk/server/sv_libk_database.lua#L113

It's derived from how DarkRP used to do it. The queries can end up being fairly long when they are generated (not sure if this could be related)

**Comment by kklouzal** [comment]
I'm having an issue where I'll try to submit a specific query multiple times with no response. mysqloo does not call onError() nor onSuccess(). Something happens after calling send() that stops the query from completing.

It seemed to start happening after I upgraded to version 8.0 but that may just be a coincidence.

**Comment by Kamshak** [comment]
This error should be gone in the next gmod version https://github.com/Facepunch/garrysmod-issues/issues/3452

**Comment by kklouzal** [comment]
Sorry I switched over to using procedures and this solved the problem. I would still suggest updating the library against mysql version 8.0
