### ISSUE TITLE
errors are ass in callbacks

### ISSUE THREAD

**Issue by meepen** [FredyH/MySQLOO#21]
i'd recommend not using pcall and using call, or at least push AdvancedLuaErrorReporter (`debug.getregistry()[1]`) to the stack for pcall

**Comment by FredyH** [comment]
Do you have some reference that this exists on any gmod server and how it works?
I tried googling it but couldn't find anything other than one other gmod addon using it.

**Comment by meepen** [comment]
Yes in cluainterface::init it creates and stores a cluaobject which is a
index into the registry which means it should always be at that index. But
you could just use call instead

**Comment by meepen** [comment]
Sorry didn't see edits on email and you are right about it being bad to use
call

**Comment by FredyH** [comment]
Hopefully I did it correctly in 375488238393321625e0ee945d2abf89c1616b00
