### ISSUE TITLE
Update MySQLOO to support 64-bit

### ISSUE THREAD

**Issue by WinterPhoenix96** [FredyH/MySQLOO#22]
Garry's Mod is now available for testing in 64-bit on the [x86-64 branch](https://gmod.facepunch.com/f/gmoddev/ruwe/Next-Update-v8-February-2018-Update-is-out/12/#postcvqpsp). Willox [has said](https://gmod.facepunch.com/f/gmoddev/ruwe/Next-Update-v8-February-2018-Update-is-out/12/#postcvqpws) that headers for it, on Windows at least, are available [here](https://github.com/Facepunch/gmod-module-base/tree/development).

Even though headers are only available on Windows for now, I'm advocating for MySQLOO to be updated ASAP so that gamemode developers that rely on MySQLOO, such as myself, can get a head start on testing their gamemodes' compatibility and reliability with 64-bit.

**Comment by FredyH** [comment]
There's now a 64 bit branch that should work with the new 64 version

**Comment by WinterPhoenix96** [comment]
Awesome. I got it built, and it seems to be working. I'll let you know if I run into anything unexpected

**Comment by FredyH** [comment]
I just committed a new version that switches back to libmysqlclient (after switching to mariadb connector), since the mariadb connector seemed to cause hangs when reusing prepared statements. If you test you should test with that one since it seems to be a lot more stable.

**Comment by WinterPhoenix96** [comment]
Alright, I'll give it a shot. Admittedly though, I don't use Prepared Statements like, at all, right now, so I don't think I'll be a good test for that.
