### ISSUE TITLE
Question regarding q

### ISSUE THREAD

**Issue by ApertureDevelopment** [FredyH/MySQLOO#26]
Short and simple question, does q in ( as example ) ``Query.onAborted( q )`` mean the query variable itself?

so when I would have this:
```lua
local getBansQ = DB:prepare("SELECT * FROM table;")
getBansQ.variable = "Value"
function getBansQ.onData( q, data, ply )
    print(q.variable)
end

getBansQ:start()
```
that it would print ``q.variable`` on returned data?

**Comment by ApertureDevelopment** [comment]
Because I need a variable thats avaiable when onData gets called

**Comment by ApertureDevelopment** [comment]
Would it work if I would do:
```lua
local getBansQ = DB:prepare("SELECT * FROM table;")
getBansQ.variable = "Value"
function getBansQ.onData( q, data, ply )
    print(self.variable)
end

getBansQ:start()
```

that would be my only other guess

**Comment by FredyH** [comment]
Yes it refers to the same object as the query variable, so you can store variables on it and use them in the callback.

**Comment by ApertureDevelopment** [comment]
It didnt work in this context, instead of 
``getBansQ.onData`` I would need ``getBansQ:onData``

**Comment by Kefta** [comment]
Your code is referencing "self" even though self is nil since you aren't using a colon. It's either:
```
function getBansQ:OnData(data, ply)
	print(self.variable)
end
```
or
```
function getBansQ.onData(q, data, ply)
	print(q.variable)
end
```

**Comment by ApertureDevelopment** [comment]
Ah, thank you!
