### ISSUE TITLE
Allow disable of outdated version timer

### ISSUE THREAD

**Issue by meepen** [FredyH/MySQLOO#28]
I just want to use the x64 branch!!!
Or at least have it in a named timer

**Comment by FredyH** [comment]
I will probably release the x64 version on this weekend.
I assume you didn't encounter any issues when using it?

**Comment by meepen** [comment]
nope.

**Comment by WinterPhoenix96** [comment]
+1 for a proper release of 64-bit binaries. I've been using versions I've compiled myself on my production servers without issue for probably around 3 months now, so it seems stable to me

**Comment by FredyH** [comment]
The last time I wrote I was gonna release it next weekend, I actually found a major bug that was pretty bad. But since then I also haven't experienced any issues so I can probably release it this weekend (this time for real).

**Comment by WinterPhoenix96** [comment]
Awesome. Thank you very much Fredy!

**Comment by WinterPhoenix96** [comment]
Could we get an update on this by chance?
