### ISSUE TITLE
linux x64 error

### ISSUE THREAD

**Issue by Kamelots** [FredyH/MySQLOO#35]
lua_run require("mysqloo")
> require("mysqloo")...
     18996:     /srv/gmodds/garrysmod/lua/bin/gmsv_mysqloo_linux64.dll: error: symbol lookup error: undefined symbol: SSL_get_fd (fatal)

[ERROR] lua_run:1: Couldn't load module library!
  1. require - [C]:-1
   2. unknown - lua_run:1

**Comment by FredyH** [comment]
What linux distro/version are you using?

**Comment by Kamelots** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

**Comment by FredyH** [comment]
Well it seems like you are missing openssl, you can just try installing it on your machine but it should be statically linked, so I am not sure why it's still requirng that. Can you run ldd on your dll for me and show me the output?

**Comment by Seraph2** [comment]
Having the same issue here, the output looks like this:
![picture](https://user-images.githubusercontent.com/31919330/69015889-1ed2d000-0999-11ea-8d15-97b981a3c2d3.PNG)

Running on Ubuntu 18.04, OpenSSL version 1.1.1.

**Comment by emoyly** [comment]
We were trying to migrate to the 64bit beta branch on our Ubuntu 16.04 server as well, and had some of these errors too.

We had the issue of not being able to require the module, and got that very same vague error saying that it `Couldn't load module library!`, just like @Kamelots
We were trying to figure out what exactly was wrong, so we tried to compile it on a Windows machine as well, but that didn't work out either.

So after digging around a bit, we tried running the `ldd` command on the dll file, and the output looked a lot like the one posted by @Seraph2
After trying their solution (removing the `libmysqlclient.a` and installing `libmysqlclient-dev`), that made the output look like this
![output of ldd](https://user-images.githubusercontent.com/24597604/69509871-dc7e3580-0f3a-11ea-9da3-b3a7994ebee9.png)

But we still couldn't load the module on the actual server...

What ended up solving that for us, was upgrading our server from Ubuntu 16.04 to 18.04, then compiling it on a machine running that same version and distro.

**Comment by FredyH** [comment]
I reverted both the libraries back to mysql6's libmysqlclient because the new ones apparently require openssl to be linked to it, which was not documented anywhere.

Unfortunately that means that the new mysql8 authentication will not work with this library but I don't want to also add statically linked libssl because that will just cause even more issues.
