### ISSUE TITLE
Query:getData() always nil

### ISSUE THREAD

**Issue by captain1242** [FredyH/MySQLOO#4]
Hey I just noticed that query:getData() is never returning anything .. also if the query should return something (query tested with MySQL workbench). Idk if its a bug or i am doing it wrong but this is the code:

```
local BanDataQ = WoltLabCBridge.DB:query([[SELECT banned,banReason,banExpires
FROM <table>
WHERE steamID64='<sid>']])

BanDataQ:start()
local bData = BanDataQ:getData()
```

**Comment by syl0r** [comment]
You can only use getData() after the query has finished. So you either need to add a callback or call BanDataQ:wait() before using getData (not recommended)
