### ISSUE TITLE
x64 usage on Windows non-srcds

### ISSUE THREAD

**Issue by Donkie** [FredyH/MySQLOO#40]
The regular ol' `libmySQL.dll` next to hl2.exe doesn't seem to work, probably because it's a 32-bit DLL. What am I meant to use instead? You mentioned that the libraries are included in the binary but that doesn't seem to work either. I'm getting the `Couldn't load module library!` error.

**Comment by FredyH** [comment]
You are probably missing the visual studio redistributable for 2019, you can download it here:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Donkie** [comment]
Sorry for not getting back to you earlier, but installing the redist didn't work (besides I already had it).

**Comment by Donkie** [comment]
The 9.6.1 release fixed this issue for me. 👍
