### ISSUE TITLE
MariaDB - 10.2.16 to 10.2.23.

### ISSUE THREAD

**Issue by D34THC47** [FredyH/MySQLOO#43]
Hi Fredy,

  My host upgraded MariaDB from 10.2.16 to 10.2.23 and now my server won't connect via MySQLOO.

  Im using 9.6.1 and im getting this error.

  DB Connection failed! Error msg: SSL connection error: unknown error number

  when connecting with multiple things to test.. I tried Promethus, SQLWorkbench and they are just not connecting.. could this be an issue with the dll.  thank you.

**Comment by FredyH** [comment]
And it worked with 9.6.1 when you still had MariaDB 10.2.16?

What is Prometheus/SQLWorkbench?

**Comment by D34THC47** [comment]
Hi Fredy,
 
  I was on 9.6 and it all was working fine once the host updated the database it gave that error.  SQLWorkbench is an addon to access mysql and sqlite databases ingame and prometheus is a payment system for people making ingame purchases and it accessed the web database from ingame to apply the purchase.  was all workimg fine until they updated.

**Comment by FredyH** [comment]
Hmm, I don't see how that would change anything. Could you also try if it works with MySQLOO 9.5?

**Comment by D34THC47** [comment]
When I add the 9.5 dll back it acts like it does not excist and gives loads of database errors.

**Comment by D34THC47** [comment]
any update ?

**Comment by FredyH** [comment]
I tested connecting to MariaDB 10.4.12 (the latest stable version) on Windows and Linux and it worked as expected, so I'm going to assume there's either a bug in 10.2.23 or there is something wrong with your setup or the host's.

**Comment by D34THC47** [comment]
is it possible for you to test it on 10.2.23

**Comment by FredyH** [comment]
I tested it and that version works too for me
