### ISSUE TITLE
onConnectionFailed not working

### ISSUE THREAD

**Issue by NikkuMiru** [FredyH/MySQLOO#44]
So basicly i used your example file and just changed some stuff
![Anmerkung 2020-01-28 183723](https://user-images.githubusercontent.com/13827077/73289582-43e78880-41fd-11ea-84e0-d2da10625649.png)
but even with the original the function is not getting called, i test it out by just shutting down the mysql server. On the other hand the connected function works just fine, i also tryed disabling setAutoReconnect cause i thought it could be that it's just trying again all the time and not printing it cause of that.
Also result 10 from the 5+5 query isn't getting printed into the console not sure if a recent change just broke it.

**Comment by FredyH** [comment]
I just tested this and it all works as expected on my end.
Are you using version 9.6.1?

**Comment by NikkuMiru** [comment]
Yes i tryed 9.6.1 and also 9.6, i'm using windows 10 64bit.

**Comment by NikkuMiru** [comment]
I'm testing on a dedicated server on my pc with the database being in xampp

**Comment by NikkuMiru** [comment]
okay i think i know the problem, i thought onConnectionFailed will also be called when the host is completly unavailable but it seems it just gets called when the host is valid but the user/pw or database is not valid.

**Comment by NikkuMiru** [comment]
so basicly the onConnectionFailed doesn't get triggered by the host being wrong

**Comment by FredyH** [comment]
It should still be called, but only after a timeout has occurred, which is somewhere between 30-60 secs I think.

**Comment by NikkuMiru** [comment]
Guess have to get used to that then.
What about the Select 5+5, is that printing for you?

**Comment by FredyH** [comment]
Yes it is, that only works if you have a working database connection though.

**Comment by NikkuMiru** [comment]
Hmm i mean i have a working connection since it's just xampp..
ugh guess i will just test a bit, cause when i start the server repeatedly the connection is not even printed all the time. still thx
