### ISSUE TITLE
Error: onConnected and onConnectionFailed not getting called after running connect

### ISSUE THREAD

**Issue by jamie-simmonds** [FredyH/MySQLOO#46]
Using mysqloo 9.6 on Linux Ubuntu 18.04, both via lua_run and in a gamemode

![image](https://user-images.githubusercontent.com/5081482/75891715-17d8ac00-5e28-11ea-87ba-1e4c1a75acd4.png)

Happens both for failed connections (incorrect password) and successful connections where serverInfo() and hostInfo() return correct

**Comment by FredyH** [comment]
The callbacks are only called if the server is not hibernating, i.e. there needs to be one player on the server or a bot.

**Comment by jamie-simmonds** [comment]
@FredyH Thanks - That actually makes a lot of sense and spawning a bot immediately fixed the issue.

**Comment by bigdogmat** [comment]
This can also be resolved setting `sv_hibernate_think` to 1
