### ISSUE TITLE
Mysql integration with gmod not working anymore with 9.5 on linux

### ISSUE THREAD

**Issue by Octonath** [FredyH/MySQLOO#47]
Since the update the gmod addon not working with 9.6 mysqloo and the libmysqlclient.so.18 was deleted so if anyone have this file can you give me pls ?

**Comment by FredyH** [comment]
32 or 64 bit?

**Comment by Octonath** [comment]
64 bit

**Comment by FredyH** [comment]
It's working just fine for me on the latest x64 update. What exactly is causing problems?

**Comment by Octonath** [comment]
In the 9.6 update gmod addon wont work so we take the 9.5 version but it need libmysqlclient.so.18 and it has been deleted so we cant use it

**Comment by FredyH** [comment]
What gmod addon?

**Comment by Octonath** [comment]
Blogs, Awarn3, and Darkrp i have not verified yet

**Comment by Octonath** [comment]
And Garry's mod Jukebox

**Comment by FredyH** [comment]
What issues are you having with them?

**Comment by Octonath** [comment]
On server launch they just they Mysqloo not find

**Comment by Octonath** [comment]
And they dont create their files

**Comment by FredyH** [comment]
Then that's very unlikely to be a problem with this library. Presumably you have placed the file in the wrong folder, downloaded the wrong version (64 bit for 32bit or vice versa) or have a permission issue on the file.

**Comment by Octonath** [comment]
I have asked for the 64 or 32 bit version to the server host and he said me that the server is in 64 bit and we placed it in lua/bin and we have tested in 9.5 this work perfectly so if you have the libmysqlclient.so.18 file this while be very helpful to me because we have tested the 9.6, renamed the file and that do not work so pls can you give us the file ?

**Comment by FredyH** [comment]
You can find the files here: https://github.com/FredyH/MySQLOO/tree/c54ed5a13d4ffa35c7661d3483dc1df2c2f3cb0d/MySQL/lib/linux

This is definitely not an issue with the library though, unless you are using an extremely outdated linux version.
