### ISSUE TITLE
MySQLOO 9.6.1 64-bit issue (Windows)

### ISSUE THREAD

**Issue by Synntaxx** [FredyH/MySQLOO#48]
I recently tried installing MySQLOO 9.6.1 on my dedicated server and I placed the gmsv_mysqloo_win64.dll into my garrysmod/lua/bin folder but I keep getting this error when I use require("mysqloo") in any script; `Couldn't include file 'includes\modules\mysqloo.lua' (File not found)`
 
I didn't encounter this issue when running the 32 bit version of 9.6.1, is this just an issue of gmod being gmod, or didn't I install the 64-bit version correctly?

**Comment by FredyH** [comment]
Are you sure you are running the 64 bit version of srcds? Even when you have 64 bit version installed you have to make sure you start srcds_win64.exe rather than the other one.
