### ISSUE TITLE
Phpmyadmin won't connect to gmod database

### ISSUE THREAD

**Issue by Invilein** [FredyH/MySQLOO#49]
did all it needed

`RP_MySQLConfig.EnableMySQL = true -- Set to true if you want to use an external MySQL database, false if you want to use the built in SQLite database (garrysmod/sv.db) of Garry's mod.
RP_MySQLConfig.Host = "localhost" -- This is the IP address of the MySQL host. Make sure the IP address is correct and in quotation marks (" ")
RP_MySQLConfig.Username = "root" -- This is the username to log in on the MySQL server.
                                -- contact the owner of the server about the username and password. Make sure it's in quotation marks! (" ")
RP_MySQLConfig.Password = "MyPasswordHere" -- This is the Password to log in on the MySQL server,
                                    -- Everyone who has access to FTP on the server can read this password.
                                    -- Make sure you know who to trust. Make sure it's in quotation marks (" ")
RP_MySQLConfig.Database_name = "DarkRP" -- This is the name of the Database on the MySQL server. Contact the MySQL server host to find out what this is
RP_MySQLConfig.Database_port = 3306 -- This is the port of the MySQL server. Again, contact the MySQL server host if you don't know this.
RP_MySQLConfig.Preferred_module = "mysqloo" -- Preferred module, case sensitive, must be either "mysqloo" or "tmysql4". Only applies when both are installed.
RP_MySQLConfig.MultiStatements = false`

**Comment by FredyH** [comment]
This seems like an issue with that addon, I am also not sure exactly what the problem is supposed to be.

**Comment by Invilein** [comment]
[DarkRP] gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:132: Module not found!
  1. require - [C]:-1
   2. loadMySQLModule - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:132
    3. unknown - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:141
     4. include - [C]:-1
      5. unknown - gamemodes/darkrp/gamemode/init.lua:42


[DarkRP] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/motd/sv_init.lua:14: attempt to index global 'MySQLite' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/motd/sv_init.lua:14
   2. include - [C]:-1
    3. AddCSLuaFolder - gamemodes/darkrp/gamemode/modules/fadmin/sv_fadmin.lua:37
     4. unknown - gamemodes/darkrp/gamemode/modules/fadmin/sv_fadmin.lua:47
      5. include - [C]:-1
       6. unknown - gamemodes/darkrp/gamemode/init.lua:93

**Comment by Kefta** [comment]
Where did you place the dll and what did you title it?

**Comment by Invilein** [comment]
lua/bin

**Comment by Kefta** [comment]
What's the title of the dll?

**Comment by Invilein** [comment]
gmsv_mysqloo_linux.dll

Am Mo., 23. März 2020 um 03:45 Uhr schrieb Collin (code_gs) <
notifications@github.com>:

**Comment by Invilein** [comment]
gmsv_mysqloo_linux.dll

**Comment by Kefta** [comment]
Is the server running on the main or x64 branch? What OS is the server running on?

**Comment by Invilein** [comment]
Linux Ubuntu 16.04

Am Mo., 23. März 2020 um 14:33 Uhr schrieb Collin (code_gs) <
notifications@github.com>:

**Comment by Kefta** [comment]
> Is the server running on the main or x64 branch?

**Comment by Invilein** [comment]
Ubuntu 16.04 minimal

**Comment by Kefta** [comment]
That doesn't answer the question, but I'm assuming since you are unaware of what the x64 branch is, you're on the main branch. I'm unsure of what the problem is since the module is in the correct folder and named properly, but the error you posted is from failing to load the dll since the server doesn't see it.

I currently have an Ubuntu local server with mysqloo installed and it loads fine so it must be something on your end. Try running this in console and report back the result:
```
lua_run print(file.Exists("bin/gmsv_mysqloo_linux.dll", "LUA"))
```

**Comment by FredyH** [comment]
If you are still having the issuee, you might need vcredist 2008.
