### ISSUE TITLE
Couldn't load module library!

### ISSUE THREAD

**Issue by Rowie47** [FredyH/MySQLOO#51]
After a fresh install of my gmod server running darkrp ( everything has the latest version )

I'm getting these errors: `[ERROR] gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:132: Couldn't load module library!`

`attempt to index global 'MySQLite' (a nil value)`

OS: Windows 10 Pro x64 ( Version 1909 ) ( Latest build )
I have installed gmsv_mysqloo_win64.dll at garrysmod\lua\bin

EDIT:
I have tried using both x64 & x32, separately and together versions 9.6.1 and 9.5

**Comment by FredyH** [comment]
It works for me, I just tested it on the latest version on windows 10, both 64 and 32 bit.
Either you placed it in the wrong folder or the library is broken.

**Comment by Rowie47** [comment]
How is the library broken?

**Comment by FredyH** [comment]
For anyone having the same issue it appears that the library requires vcredist 2008.
