### ISSUE TITLE
Does this module allow for secure connections?

### ISSUE THREAD

**Issue by viral32111** [FredyH/MySQLOO#52]
Heya,

As the title states, I would like to know if I can connect securely using SSL/TLS certificate & private key files to a MySQL server like you usually can with [ssl_ca, ssl_cert, ssl_key, etc](https://dev.mysql.com/doc/refman/8.0/en/using-encrypted-connections.html#using-encrypted-connections-client-side-configuration) on other MySQL clients.

If this is possible, can you provide me with some demo code on how I would specify the cert & key?

Thanks, viral32111 :)

**Comment by FredyH** [comment]
Using certificates is currently not possible. I am fairly certain the client does use encryption if available but you cannot establish identity of the server.
Maybe I should add this in the next version.

**Comment by WinterPhoenix** [comment]
A quick note, with a MySQL 8 Server target, I'm getting this with SSL turned on:
`SSL connection error: unknown error number`

Without X509 certificate stuff.

**Comment by FredyH** [comment]
Closing in favor of #60
