### ISSUE TITLE
Couldn't load module MySQLOO

### ISSUE THREAD

**Issue by Minc3** [FredyH/MySQLOO#53]
Hello,
The latest version of mysqloo doesn't load for me.
I know its installed correctly.
I have tried both 32/64 

All my add-ons are saying this:
MySQL Error: MySQLOO modules aren't installed properly!
Couldn't load module library!

Details:
I have vcredist 2008 x86/x64 installed
OS: windows server 2019
srcds location: i don't have the old libmySQL.dll
INSTALL Location: garrysmod\lua\bin\gmsv_mysqloo_win32.dll

**Comment by FredyH** [comment]
Have you also installed all the other vcredists?

**Comment by Minc3** [comment]
What ones do i need?

**Comment by Minc3** [comment]
This is now fixed
You don't need vcredist 2008 x86/x64!
You just need the lasted one installed.
https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads
