### ISSUE TITLE
Just wanted to say thanks for the headache.

### ISSUE THREAD

**Issue by Hootsir** [FredyH/MySQLOO#54]
No idea how to install this stuff from a newb perspective. Extremely not user friendly. -.- So aggrivating been trying to get this working for 4 hours. Catch4 or Catch5 just closes, I have to confusingly compile stuff... -.- Just make it easier to install for god sake.. I dont know what I am doing with C++ and all that.

**Comment by FredyH** [comment]
Hi, compiling yourself is not really something meant for newbs, C++ in general is just a hot mess that is extremely hard to use.
Anyways, if you at least provided the problems you are having ,we might be able to help you.
Also what is catch4?

**Comment by Hootsir** [comment]
I’m just trying to get MySQL for DarkRP to hook up. I downloaded your folder and don’t even know what to do because there’s no .exe... I just want to link my servers via sql 😭

**Comment by SaturdaysHeroes** [comment]
I actually believe mysqloo is pretty well-documented, especially if you only want to install it. If you want to set it up for your darkrp server, all you should have to do is drop the binaries in the correct place.

**Comment by Hootsir** [comment]
the thing is, I don’t have a mysqloo installed or if that makes sense, I was under the impression it was something different.
The binaries are dropped in and nada, I get the same error the other guy had about mysqlite. I’m just baffled...

**Comment by SaturdaysHeroes** [comment]
If you don't know what you're doing then it's not mysqloo's fault, seriously. You can either try to learn or hire someone to do it for you, I've been using mysqloo for ages and never had an issue with it.

**Comment by viral32111** [comment]
It's always worked fine for me, just download [the latest release](https://github.com/FredyH/MySQLOO/releases) for your server's OS & architecture, then place it in `garrysmod/lua/bin` (as documented [here](https://github.com/FredyH/MySQLOO#install-instructions), then inside your script just call:

```lua
require("mysqloo")
```

The rest of the documentation is [here](https://github.com/FredyH/MySQLOO#documentation), or have a look at [some of the examples](https://github.com/FredyH/MySQLOO/tree/master/Examples) as a guide.

**Comment by Hootsir** [comment]
I’m saying that it needs to be more user friendly. But anyway good talk I guess.
