### ISSUE TITLE
Please remove version check

### ISSUE THREAD

**Issue by Rubberbandits** [FredyH/MySQLOO#58]
The version check is nice, but at least add some way to disable it. Server hangs for up to two minutes on boot trying to check the version of the module.

**Comment by FredyH** [comment]
Why would the version check hang on boot? It should run asynchronously using gmods http library.

**Comment by Rubberbandits** [comment]
im not entirely sure why it does but i think its because during boot, chromium isnt running async. i just know that once a player joins, the server hangs on the version check and ents think for like 55 seconds. 

server resumes once the version check finishes

**Comment by viral32111** [comment]
I've made a fork with the code changes for an optional version checker. It's simple to turn on or off, just add `sv_mysqloo_versioncheck 0/1` to the `server.cfg` file or alike.

@Rubberbandits Can you try test this and see if it fixes your issue? If it does, I'll make a PR.

[Download](https://github.com/FredyH/MySQLOO/files/4567958/Binaries.zip) (I've only tested Windows 32-bit).

**Comment by FredyH** [comment]
@viral32111 Sounds good, feel free to make a PR and I'll look at it once I am back home

**Comment by Rubberbandits** [comment]
the launch of our new gamemode is today, so it might not be tested until later tonight. will let you know, we're running ubuntu so we'll find out if the module works on linux32
