### ISSUE TITLE
MySQLOO ver 9.6.1 doesnt loads into the server

### ISSUE THREAD

**Issue by thescs** [FredyH/MySQLOO#64]
Hello. I'm running GMod server on Windows Server 2019 x64. Version 9.6.1 doent works for me.

> [ERROR] lua_run:1: Couldn't load module library!
  1. require - [C]:-1
   2. unknown - lua_run:1

Otherwise previous release 9.6 works fine!

**Comment by FredyH** [comment]
You are probably missing some vcredist versions.

**Comment by thescs** [comment]
I have all VC redists installed. 32 and 64 bits.

пн, 25 мая 2020 г., 03:55 FredyH <notifications@github.com>:

**Comment by uGamers** [comment]
Confirmed does not load

**Comment by FredyH** [comment]
It does load for me so you also must be missing some vcredist version. Use dependency walker (https://www.dependencywalker.com/) to see what's missing.

**Comment by uGamers** [comment]
I've tried both window and Lunix what is needed for lunix so I don't have to buy another VPS to just run Gmod?

**Comment by uGamers** [comment]
Guess it does work just find on window but whats the trick for Lunix?

**Comment by FredyH** [comment]
It should work on linux but you need at least Ubuntu 16.04 or a similarly up to date distro.

**Comment by uGamers** [comment]
I got 

Operating system
Ubuntu Linux 16.04.6
Kernel and CPU
Linux 4.11.8-041108-generic on x86_64

Note: I have both a Window VPS and a Linux Dedicated server
Window works Linux does not.

Ive copied the configs from my working Window server to the Linux server Minus the lua/bin file that I downloaded for lunix here. I tried both 64bit and 32bit when I join the server im out of place and get this error 
[DarkRP] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
  1. Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
   2. unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62
  
If I set RP_MySQLConfig.EnableMySQL = true it give this error on Linux if I set it to false it works fine using built in SQLite Database. I made permissions on box 777 for all files just to see if it was permission related but no.

**Comment by uGamers** [comment]
Another update 

Strange using https://github.com/KryptonNetworks/MySQLOO
gmsv_mysqloo_linux.dll  Add files via upload 4 months ago

**Comment by FredyH** [comment]
You should try running it on ubuntu 18.04 if you can, but 16.04 should work too.
Is there an error when requirign the module?

**Comment by uGamers** [comment]
Nevermind I lied lol

**Comment by uGamers** [comment]
The only error I was getting was

[DarkRP] gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23: attempt to index local 'jobTable' (a nil value)
Call - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:23
unknown - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:62

Like it could not get things from the database or connect. But with same config on windows it works fine.

**Comment by uGamers** [comment]
Ok After hours of Testing I found out with upgrading to PHP version: 7.2.24 and  ubuntu 18.04 it works.

I would recommend putting this in your install guide not sure if it would still work with 16.04 and ubuntu 18.04 as I upgraded already so maybe just put in there make sure you have at least php7.1 or something lol.

**Comment by uGamers** [comment]
Ok after hour of testing I found out.

It worked after I upgraded to PHP version: 7.2.24 

I would add that they should have atleast php7.1 in your install guide.

I'm not sure if having Ubuntu Linux 18.04.4 is a factor as I upgraded before testing the new php version. 

Sum this up as if they have Ubuntu Linux 18.04.4 with PHP version: 7.2.24 it will work.

**Comment by viral32111** [comment]
Seeing PHP as a "dependency" of this module is one thing I didn't expect 😄

**Comment by FredyH** [comment]
Thankfully it's not, but if installing php worked for him, that's great.

**Comment by uGamers** [comment]
Did not install PHP I upgraded it.

**Comment by viral32111** [comment]
> I'm not sure if having Ubuntu Linux 18.04.4 is a factor as I upgraded before testing the new php version.

It was probably the upgrade to Ubuntu 18.04 that fixed it for you, not the PHP upgrade. Unless an upgrade of an already installed PHP extension such as mysqli also pulled new mysql libs for you. :thinking:

Either way, at least it's fixed.
