### ISSUE TITLE
Can you stop the spam of this message please its DRIVING ME INSANE

### ISSUE THREAD

**Issue by physios** [FredyH/MySQLOO#65]
Your server is using an outdated mysqloo9 version
Download the latest version from here:
https://github.com/syl0r/MySQLOO/releases 

I had to patch my own dll

**Comment by FredyH** [comment]
Why is it driving you insane? Have you considered updating to stop yourself from going insane?

**Comment by physios** [comment]
Yes and it caused my server to crash on boot. Can you atleast make it an option or just make it say that ONCE. No need to spam it every 5 minutes just saying...

**Comment by physios** [comment]
i could do that for you if you want

**Comment by FredyH** [comment]
I have already merged a pull request that disables the version checker, I will release it soon. However, that version will be for the version of MySQLOO that presumably crashes you, so even that will presumably not help you out unfortunatley.

However, if you are using 64 bit, then I will release a new version with mysql 8 support soon, that should not crash you anymore, so I suggest until then you use your patched version.

Either way, for any reasonably large server, the normal log messages should outnumber the ones produced by MySQLOO by a massive margin, but maybe you just don't log stuff to the console at all?

**Comment by physios** [comment]
> I have already merged a pull request that disables the version checker, I will release it soon. However, that version will be for the version of MySQLOO that presumably crashes you, so even that will presumably not help you out unfortunatley.
> 
> However, if you are using 64 bit, then I will release a new version with mysql 8 support soon, that should not crash you anymore, so I suggest until then you use your patched version.
> 
> Either way, for any reasonably large server, the normal log messages should outnumber the ones produced by MySQLOO by a massive margin, but maybe you just don't log stuff to the console at all?

It's a dev server, I do use a dedicated server 64bit, and I am fine with that thank you
