### ISSUE TITLE
I'm having a weird issue going on rn involving this module

### ISSUE THREAD

**Issue by VaasKahnGrim** [FredyH/MySQLOO#66]
So right now I have only 2 things which are using mysql on my server. I have an addon which was made by a company called WiltOS which is a lightsaber combat addon, and the other thing on my server which has mysql used is my gamemode that I've built. The lightsaber addon uses mysqloo for its stuff, however the gamemode uses tmysql4 instead. I'm not yet sure which of the 2 modules is causing this to happen but this is what I'm noticing. in the console of srcds it would seem that everything is fine, however I attached to process in visual studio 2019 to look into something else and I noticed this being spit out alot into the output section of the debugger: `Exception thrown at 0753A3DB2 in srcds.exe: Microsoft C++ exception: MySQLException at memory location 0x287BF884`

Any idea what exactly is going on here?

P.S. I don't really have full source code access to the lightsaber addon. DRM is too strong lol

**Comment by Kefta** [comment]
Why not ask @WiltOS directly?

**Comment by FredyH** [comment]
Exceptions being thrown is normal and happens whenever an error occurs in a query or similar. It would only be an issue if the server crashed as a result of it.

**Comment by KingDavidW** [comment]
Run the mysqloo module on a test bench without my addon mounted and see if you get the exception.

I haven't seen this exception before but then again most people aren't looking for this. I just think it's jumping the gun to come here if you haven't validated it's even an issue with this module alone

**Comment by VaasKahnGrim** [comment]
It seems the error isn't popping up with just the module on a fresh sandbox server on its own being used in a simple query for retrieiving a table. I'm thinking maybe its related to the other module being used in the gamemode. I'll try testing with just the lightsaber addon and mysql to see if it causes the exception to be thrown and if not then I'll look into figuring out if the other module is causing it next
