### ISSUE TITLE
"SSL connection error: unknown error number" even after setting SSL not mandatory

### ISSUE THREAD

**Issue by BitCrack** [FredyH/MySQLOO#67]
I am using MySQLOO 9.6.1 and MariaDB 10.5.4
I wanted to use SSL for my database, but after setting up LibK to use my database, this error popped up "[LibK] Connection failed to LibK(USER@IP): SSL connection error: unknown error number", which was mentioned in issue #60
Problem is that this kept occurring EVEN AFTER I made SSL not required for the user that I'm connecting with, using `ALTER USER@IP REQUIRE NONE;`. Is there a fix without disabling SSL for the whole database?

**Comment by FredyH** [comment]
I don't believe this can be fixed without upgrading to the mysql 8 connector. The changes are already commited to the master branch, I will probably release the update some time soon.

**Comment by SandeQ** [comment]
> I don't believe this can be fixed without upgrading to the mysql 8 connector. The changes are already commited to the master branch, I will probably release the update some time soon.

if you could release it ASAP please, only this error is stopping us from moving to x64 version of gmod server and resolving the lags problem caused by the x32 version.

**Comment by viral32111** [comment]
If the changes are already on the master branch, you can compile it yourself and see if it works for you. I understand that compiling isn't exactly easy for the average person, but it's probably better to do this than go ahead and release a full version if there's still anything left to be done (there might not be of course, but judging by what was said earlier and considering it isn't released yet, I'm assuming there's still things left to do).

**Comment by SandeQ** [comment]
Well, i forgot about it, right now i've compiled it, but i've got some errors


1>------ Kompilacja rozpoczęta: Projekt: MySQLOO, Konfiguracja: Release x64 ------
1>Database.cpp
1>I:\sande\Pulpit\gmod\MySQLOO\source\Database.cpp(115,41): warning C4244: "argument": konwersja z "size_t" do "double", możliwa utrata danych
1>GMModule.cpp
1>I:\sande\Pulpit\gmod\MySQLOO\source\GMModule.cpp(63,48): warning C4244: "argument": konwersja z "unsigned __int64" do "double", możliwa utrata danych
1>IQuery.cpp
1>I:\sande\Pulpit\gmod\MySQLOO\source\IQuery.cpp(172,66): warning C4267: "argument": konwersja z "size_t" do "unsigned long", możliwa utrata danych
1>LuaObjectBase.cpp
1>PingQuery.cpp
1>PreparedQuery.cpp
1>I:\sande\Pulpit\gmod\MySQLOO\source\PreparedQuery.cpp(136,35): warning C4267: "inicjowanie": konwersja z "size_t" do "unsigned int", możliwa utrata danych
1>I:\sande\Pulpit\gmod\MySQLOO\source\PreparedQuery.cpp(214,52): warning C4267: "=": konwersja z "size_t" do "unsigned long", możliwa utrata danych
1>Query.cpp
1>I:\sande\Pulpit\gmod\MySQLOO\source\Query.cpp(178,61): warning C4267: "argument": konwersja z "size_t" do "unsigned int", możliwa utrata danych
1>ResultData.cpp
1>Transaction.cpp

All those error says "converting from "typea to "typeb", there is a possibility of data loss"

I'm not sure if my visual 2019 hadn't broke something o.O

**Comment by FredyH** [comment]
All of these messages are just warnings, I think all or most caused by us converting integers to doubles because lua only supports doubles. So you can just ignore these and it seems like it compiled correctly.

**Comment by FredyH** [comment]
I have also uploaded a beta release that includes prebuilt binaries.

**Comment by BitCrack** [comment]
Seems to work fine, no errors regarding SSL so far. I'm considering this issue resolved.
