### ISSUE TITLE
Mysqloo don't work. 

### ISSUE THREAD

**Issue by MiisterChipsSs** [FredyH/MySQLOO#69]
Hello! First of all, I apologize for my poor English.

I came to see you because my mysqloo just doesn't work. 

`lua_run require("mysqloo")
require("mysqloo")...
Couldn't include file 'includes/modules/mysqloo.lua' (File not found) (@lua_run (line 1))
[ERROR] lua_run:1: Module not found!
1. require - [C]:-1
2. unknown - lua_run:1`

I installed "gmsv_mysqloo_linux64.dll" in "/garrysmod/lua/bin" but it doesn't load.

The problem would come from the fact that I use a panel to manage my game servers (Pterodactyl)? Otherwise I would have missed something? Or it's just my linux distribution ( Ubuntu 18.04.4 LTS)

Thank you

**Comment by fizioterapia** [comment]
You're probably running x86 version of Garry's Mod server.
Try to install x86 version of MySQLOO module.

**Also there is a note:**
If you're unsure of your server's operating system and architecture, type lua_run print(jit.os, jit.arch) into the server's console to find out. The output will be something similar to Windows x86 (x86 is 32-bit, x64 is 64-bit).

**Comment by MiisterChipsSs** [comment]
Damn... it works. I don't understand why the server was 32-bit, but it's fine!

Sorry for my inability and thank you.

**Comment by viral32111** [comment]
> I don't understand why the server was 32-bit, but it's fine!

Even if you have an x64 operating system, the server will always be running x86 unless you explicitly run your server on the x86-64 branch and launch it via the srcds_x64 executable.

(Apologies for commenting on a closed thread, just trying to offer future help)
