### ISSUE TITLE
Mysqloo 9.7.0-beta-1 cannot be installed on linux

### ISSUE THREAD

**Issue by ceifa** [FredyH/MySQLOO#71]
I installed the binaries on my server:

```
root@3b64f59743d1:/# tree -f | grep mysql
|       |   |   |   |   `-- ./home/gmod/server/garrysmod/lua/bin/gmsv_mysqloo_linux64.dll
|       |   |-- ./home/gmod/server/libmysqlclient.so
```

And then I checked the luajit:

```
lua_run print(jit.os, jit.arch)
> print(jit.os, jit.arch)...
lua_run:1/0     Linux x64
```

And when I tried to require the module with `require("mysqloo")`, it throwed an error, but f I do the exactly same steps with the version `9.6.1`, it works great.

Am I doing something wrong or is it a bug?

**Comment by viral32111** [comment]
Try https://github.com/FredyH/MySQLOO/issues/68#issuecomment-656617701 to see if it helps you.

**Comment by ceifa** [comment]
> Try [#68 (comment)](https://github.com/FredyH/MySQLOO/issues/68#issuecomment-656617701) to see if it helps you.

It works! Thanks for the fast reply.
I will remain the issue open because it seems to be a bug on mysqloo.

**Comment by viral32111** [comment]
Not really a bug, one of the files in the release .zip just needs to be renamed (or some alternate compiling flags need to be set?).

I think you can also install the `libmysqlclient-dev` package which will add all the correctly named libs to your OS so you're not relying on the one shipped with the beta release. I'm not 100% sure on this though.
