### ISSUE TITLE
Couldn't load module library!

### ISSUE THREAD

**Issue by dankmolot** [FredyH/MySQLOO#72]
Please, help me with building library on linux.
I'm writed mongodb wrapper for but on linux (Ubuntu server 20.04 x64) when i try to load garry's mod library it gives an error.

I tried building 32bit libraries, but it doesn't work either.
If you know how to help, contact with me in Discord: Retro🎃#1593.

My mongodb wrapper source: https://github.com/Pika-Software/gmsv_mongodb

**Comment by viral32111** [comment]
Could you provide a few more details, such as what version of MySQLOO you're trying to use and what architecture the dedicated server is running? See the [notes](https://github.com/FredyH/MySQLOO#notes) section on the README for instructions on that last part.

**Comment by dankmolot** [comment]
Found where was the problem. Library trying find needed libraries, but can't find them because i didn't use static linking
