### ISSUE TITLE
Couldn't include file 'includes/modules/mysqloo.lua' (File not found) (@gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua (line 132))

### ISSUE THREAD

**Issue by CWright-91** [FredyH/MySQLOO#74]
Hello

Im recieving the following error and was wondering if anyone has experienced the same thing?  I've tripple check that I've done everything right but still can't seem to get it working.   Any help would be greatly appreciated.   Also, when I join the server I fall in and have no physgun.

OS:  Ubuntu 18.04.5 LTS
Architecture:        x86_64
/home/steam/server_1/garrysmod/lua/bin
gmsv_mysqloo_linux64.dll

RP_MySQLConfig.EnableMySQL = true
RP_MySQLConfig.Host = "localhost"
RP_MySQLConfig.Username = "root"
RP_MySQLConfig.Password = "MYPASSWORD" 
RP_MySQLConfig.Database_name = "darkrp"
RP_MySQLConfig.Database_port = 3306
RP_MySQLConfig.Preferred_module = "mysqloo"
RP_MySQLConfig.MultiStatements = false

[ERROR] gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:132: Module not found!
  1. require - [C]:-1
   2. loadMySQLModule - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:132
    3. unknown - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:141
     4. include - [C]:-1
      5. unknown - gamemodes/darkrp/gamemode/init.lua:42

[ERROR] gamemodes/darkrp/gamemode/modules/fadmin/fadmin/motd/sv_init.lua:14: attempt to index global 'MySQLite' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/motd/sv_init.lua:14
   2. include - [C]:-1
    3. AddCSLuaFolder - gamemodes/darkrp/gamemode/modules/fadmin/sv_fadmin.lua:37
     4. unknown - gamemodes/darkrp/gamemode/modules/fadmin/sv_fadmin.lua:47
      5. include - [C]:-1
       6. unknown - gamemodes/darkrp/gamemode/init.lua:93

[ERROR] gamemodes/darkrp/gamemode/init.lua:112: attempt to index global 'MySQLite' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/init.lua:112

Thank you

**Comment by FredyH** [comment]
You are probably running the 32 bit version of SRCDS. Try placing both the 32 and 64 bit version in the lua/bin folder and see if it works then.

**Comment by CWright-91** [comment]
Thats solved it!
Thanks!
