### ISSUE TITLE
mysqloo module not created

### ISSUE THREAD

**Issue by el9in** [FredyH/MySQLOO#75]
Installed according to the instructions: https://github.com/FredyH/MySQLOO/blob/master/README.md
Win 10 x64 but srcds show x86, i tryed x32 and x64.. configuration not created.
Have vcredist 2019, 2015...

**Comment by el9in** [comment]
ubuntu 18, the same problem

**Comment by FredyH** [comment]
I don't understand, what is the issue you are having?
