### ISSUE TITLE
MySQL Crash

### ISSUE THREAD

**Issue by OhmeP** [FredyH/MySQLOO#77]
Hey so recently my server has been crashing so i thought i'd make this  just incase you would happen to know or be able to fix it if it's something caused by your this or maybe you know what it is

Cause of crash: Query::doCallback () at ../../MySQLOO/source/Query.cpp:62

All Addons using MySQL

DarkRP
SAM Admin Mod
VoidCases
Death Screens
Xenin Inventory
Xenin Carepackages
Titlestore 2
Awarn3
Prometheus
Glorified Leveling

**Comment by FredyH** [comment]
This likely means that the crash is caused by whatever function was used as a callback. For example removing the map entity from a callback would cause this crash.
