### ISSUE TITLE
mysqloo not loading

### ISSUE THREAD

**Issue by GardenGnome164** [FredyH/MySQLOO#79]
I installed the binary module as described in the installation directions (extracted and put in bin/), but when I try to use the mysqloo library, the mysqloo table is throwing nil.

**Comment by GardenGnome164** [comment]
Couldn't include file 'includes\modules\mysqloo.lua' (File not found) (@addons/[tfa]lucky_attachments/lua/autorun/server/sv_protect.lua (line 1))

[[tfa]lucky_attachments] addons/[tfa]lucky_attachments/lua/autorun/server/sv_protect.lua:1: Module not found!
  1. require - [C]:-1
   2. unknown - addons/[tfa]lucky_attachments/lua/autorun/server/sv_protect.lua:1

**Comment by FredyH** [comment]
This means the mysqloo file was not found or placed in the correct folder. You need to place the file in the lua/bin folder, not in the bin/ folder. If that is not the problem then you probably used the 32 bit version on a 64 bit server or vice versa, so use the correct version for your server.
