### ISSUE TITLE
srcds_run_x64 mysqloo module does not start

### ISSUE THREAD

**Issue by mo3g666** [FredyH/MySQLOO#83]
There is a dedicated server with the x86-64 beta branch. When starting the server via srcds_run_x64, the library is not loaded and, accordingly, there is also no connection to the database. Please help me understand the cause of the malfunction.

**Comment by FredyH** [comment]
Can you be more specific? How do you know the library is not loaded and what operating system are you running?

**Comment by mo3g666** [comment]
The operating system is Ubuntu Server 20.04 x64 LTS. Installing this package helped:
`sudo apt-get install libmysqlclient-dev`
