### ISSUE TITLE
Linux : MYSQLOO no callback when running queries

### ISSUE THREAD

**Issue by yreibel** [FredyH/MySQLOO#87]
Hey,

Referring to this previous post, everything was working well and I had even found the issue which was not related to VCREDIST at all since I was already possessing those modules : https://github.com/FredyH/MySQLOO/issues/85

The thing is now, my code is working perfectly well on my local windows server, but when trying to implement it on my garry's mod server located on my debian 10 server, I realize that the exact same problem occurs !

If the code is perfectly functional, where does the problem can come from on linux regarding the fact that it does not go through the callback after running a query ?

Is there something related to VCREDIST even though I am pretty sure it does not exist on linux ?
Or is there a similar module that can handle it ?

Thanks.

**Comment by yreibel** [comment]
PS : i'm using MYSL 8 on my debian server and queries are working well outside garry's mod

**Comment by FredyH** [comment]
If you can send me the exact code you are running (if you want you can also add me on steam to send it to me privately), I can take a look and see if it works for me when using mysql 8.

**Comment by yreibel** [comment]
I added you on Steam !
