### ISSUE TITLE
MYSQL brake server on Mapchange.

### ISSUE THREAD

**Issue by GoldWaffel** [FredyH/MySQLOO#88]
Hey Guys, 
First I am sorry for my Bad english, I am german...
My Problem is, if i use any addon with MYSQL connection, the server is braking on a mapchange.
This code is showing up: https://ibb.co/GF95HcX

Can someone help me please🥺

Greets 
Noah aka. GoldWaffel

Same Problem as here: https://github.com/FredyH/MySQLOO/issues/45

**Comment by FredyH** [comment]
What version of the module and operating system are you using?

**Comment by GoldWaffel** [comment]
I am using the latest Version of the Module, an the operating system is: 5.7.35-0ubuntu0.18.04.1

**Comment by GoldWaffel** [comment]
Maybe I should try a earlier version, but which one?

**Comment by FredyH** [comment]
You can also try the latest beta release.
Please also attach the debug.log entry from when it crashes. You need to pass the -debug flag to srcds and have gdb installed.

**Comment by GoldWaffel** [comment]
The gdb is already installed and what do you mean with -debug flag

**Comment by FredyH** [comment]
If you can add the -debug flag to the srcds start command it will automatically generate a debug.log entry.
If this is not possible, it is almost impossible to debug unfortunately.
You can try downloading the latest [beta release](https://github.com/FredyH/MySQLOO/releases/tag/9.7.0-beta-6), maybe it is not an issue with that version anymore.

**Comment by GoldWaffel** [comment]
Ok I will try later.
