### ISSUE TITLE
Gmod: Mysqloo Modul not found

### ISSUE THREAD

**Issue by Gamer688** [FredyH/MySQLOO#89]
Hi guys!
I've bought an addon for some time.
(gextension)
This needs Mysqloo to work.
So I put the module in the folder: /gameserver/garrysmod/lua/bin and it doesn't work (the addon doesn't find it). 
I have tried many things such as different 
Mysqloo versions. by the way my gmod server uses 
Linux 64 bit.
And by now I have no idea what i can do.

error:

[gextension] addons/gextension/lua/gextension/server/sv_mysql.lua:35: Module not found!
  1. require - [C]:-1
   2. InitSQL - addons/gextension/lua/gextension/server/sv_mysql.lua:35
    3. v - addons/gextension/lua/gextension/server/sv_main.lua:20
     4. Run - lua/includes/modules/hook.lua:84
      5. unknown - addons/gextension/lua/autorun/gextension_load.lua:74

**Comment by Gamer688** [comment]
Sorry my english is not so good.

**Comment by FredyH** [comment]
Make sure that you download both the 64 bit and 32 bit version, you can also try using the latest beta release.
If none of that works, please let me know what linux distribution you are using.

**Comment by Gamer688** [comment]
I just asked the server hoster what I can say now. That this runs on Linux and I have installed and tried more times the 32 bit and 64 bit version. But this has done nothing at all.

**Comment by FredyH** [comment]
Please ask your host for support in that case. The module can be found on my local and live server. Your module is either misplaced or there is some other configuration issue with the host.
