### ISSUE TITLE
[LibK] Connection failed to Update > SSL connection error: unknown error number

### ISSUE THREAD

**Issue by Neonsy** [FredyH/MySQLOO#90]
LibK cannot connect to my MySQLServer and I don't know what to do.

PhpMyAdmin is secured with a certificate so that might have something to do with it but I'm not sure.

If you need more information feel free to ask. 

[libk_error.txt](https://github.com/FredyH/MySQLOO/files/7452645/libk_error.txt)

**Comment by Niko1331** [comment]
+1
