### ISSUE TITLE
The problem with the crash of the latest version

### ISSUE THREAD

**Issue by dok441** [FredyH/MySQLOO#95]
Hello, I would like to report a problem with the faucet in the latest version of mysql. This usually happens after changing the maps randomly. After the maps has changed, either the server breaks down completely and nothing works, or writes this error and the server crashes.
Lua Panic! Something went horribly wrong!

"attempt to index a number value"Lua Panic! Something went horribly wrong!

"attempt to index a number value"
Mode https://github.com/Arizard/deathrun
OS: debian 11
The problem was on both 64x and 32 bit.

**Comment by FredyH** [comment]
Can you check both the debug.log file and the crashes folder if they contain any info about the crashes?

**Comment by dok441** [comment]
https://pastebin.com/b4NbnCrf There is nothing special in the logs, the latter is just a connection to mysql

**Comment by FredyH** [comment]
Can you try using the 32 bit version (i.e. not the 32 bit version on the 64 bit beta branch) and see if it also crashes there?

**Comment by dok441** [comment]
I checked the server not on beta 32, as a result, the mode with errors just breaks there.
https://pastebin.com/KtuWJW1n As a result, now I get a broken server sometimes after changing the maps.
https://steamcommunity.com/sharedfiles/filedetails/?id=2206993805 This hook causes an error most often, perhaps it's the case.

**Comment by NiXyos** [comment]
hello, I have the same problem when I put the last version, it cannot find the connection to the base

**Comment by FredyH** [comment]
I published a new version that might have fixed this issue: https://github.com/FredyH/MySQLOO/releases/tag/9.7.2-beta-1
Please report back if that one still crashes.

**Comment by NiXyos** [comment]
does not connect with MySQLOO 9.7.2, MySQLOO 9.6 version works fine except it spam and asks to download the latest version 

[libk] addons/libk/lua/libk/server/sv_libk_database.lua:293: attempt to index field 'MySQLDB' (a nil value)
  1. prepareForSQL - addons/libk/lua/libk/server/sv_libk_database.lua:293
   2. findAllDbByField - addons/libk/lua/libk/server/sv_libk_model.lua:241
    3. findByPlayer - addons/libk/lua/libk/server/sv_libk_model.lua:554
     4. fn - addons/libk/lua/libk/server/sv_libk_player.lua:3
      5. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by FredyH** [comment]
The error you are getting is unrelated to crashes but rather due to an outdated version of mysqloolib being used by LibK.

I have created a [pull request](https://github.com/Kamshak/LibK/pull/39) that provides an updated version in LibK.
However, it needs some more adjustments by the LibK maintainer.
For now, you can update the file like I did in the pull request and also add require("mysqloo") into the first line, then it should work in your case.

**Comment by FredyH** [comment]
Potentially fixed in [9.7.2](https://github.com/FredyH/MySQLOO/releases/tag/9.7.2)
