### ISSUE TITLE
Constant printing

### ISSUE THREAD

**Issue by kasper-dev** [FredyH/MySQLOO#96]
Hiya, I'm trying to use the latest version with XLIB GDBC SQL wrapper but it does not work as u pointed out in the notes of the latest release so as a solution  I'm using 1 version older however the constant printing of this version is outdated is really annoying any way to disable it?

**Comment by bigdogmat** [comment]
`sv_mysqloo_versioncheck 0`

**Comment by kasper-dev** [comment]
> 

Thank you so much, have a great rest of your night/day.

**Comment by kasper-dev** [comment]
> 

Wait were would i put  this, my bad lol.

**Comment by FredyH** [comment]
Sadly, the version check variable was only introduced with 9.7.0, so there is no way to disable it in 9.6.1 iirc.
The best course of action is probably to adapt the library. The change should be relatively easy, but I can help you with it if you add me on steam/discord.

**Comment by kasper-dev** [comment]
> Sadly, the version check variable was only introduced with 9.7.0, so there is no way to disable it in 9.6.1 iirc.
> The best course of action is probably to adapt the library. The change should be relatively easy, but I can help you with it if you add me on steam/discord.

No problem, I'll add you on discord once I wake up its currently midnight for me thanks.
