### ISSUE TITLE
Nill Value for AutoReconnect

### ISSUE THREAD

**Issue by FabriSAM** [FredyH/MySQLOO#97]
Hi I have a problem with the autoreconnect function.

After updating on many scripts it gives me this problem.

attempt to call method 'setAutoReconnect' (a nil value)

**Comment by bigdogmat** [comment]
It's currently called `setSQLAutoReconnect`, probably a typo but for the mean time that'll work

https://github.com/FredyH/MySQLOO/blob/fd2ecc4a1cbed377d20db2e5470e7bf2b8c23571/src/lua/LuaDatabase.cpp#L258

**Comment by FredyH** [comment]
When I did a refactor it also erroneously renamed the string constant. I already pushed the change and I will release an updated version later today.

**Comment by FabriSAM** [comment]
Thx all can u allert me when u update ?? i love u all for your work

**Comment by FredyH** [comment]
Fixed in 9.7.1
