### ISSUE TITLE
Request: Query:getDB(), Query:getSQL()

### ISSUE THREAD

**Issue by 2048khz-gachi-rmx** [FredyH/MySQLOO#98]
word
Currently using the lua equivalent, but (imo) it should be in the module itself
```lua
local DB = FindMetaTable("MySQLOO Database")
local QRY = FindMetaTable("MySQLOO Query")

DB._realQuery = DB._realQuery or DB.query

function DB:query(str)
	local qObj = self:_realQuery(str)

	qObj._fromDb = self
	qObj._strQry = str

	return qObj
end

function QRY:GetSQL()
	return self._strQry
end

function QRY:GetDB()
	return self._fromDb
end
```

**Comment by FredyH** [comment]
This would be easy to add. However, what would be the use case for being able to get the database of a query or the query string?

**Comment by 2048khz-gachi-rmx** [comment]
Don't need it anymore, thought the db needs reconnecting manually if connection is lost (it doesn't), so i wanted to keep a reference around in the query object itself in case that's necessary
